spring: 
  thymeleaf: 
    prefix: classpath:/templates/
    cache: false
  mvc:
    favicon:
      enabled: true
#    locale: pt_BR
    date-format: dd/MM/yyyy
  h2.console:
    enabled: true
    path: /db
  jpa: 
    show-sql: true
    hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  multipart:
    maxFileSize: 1024KB
    maxRequestSize: 5MB
  mail:
      host: smtp.gmail.com
      username: sellstockapp@gmail.com
      password:  sellstockapplication
      port: 587
      properties.mail.smtp.starttls.enable: true
    
server: 
  port: 8080
  contextPath: /
  
#logging:
#  level:
#    root: WARN
#    org.springframework.web: WARN
#    org.hibernate: WARN
#  file: logs/sistema.log

